sylius_resource:
    resources:
        app.book:
            classes:
                model: AppBundle\Entity\Book

fos_rest:
    view:
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
